2020-12-18 17:04:33,088 com_data.py[line:35] INFO {'串口连接异常：': SerialException(2, "could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'")}
