2020-12-23 18:55:30,816 com_data.py[line:35] ERROR {'串口连接异常：': SerialException("could not open port '/dev/ttyUSB0': FileNotFoundError(2, '系统找不到指定的路径。', None, 3)")}
2020-12-23 19:03:09,705 com_data.py[line:35] ERROR {'串口连接异常：': SerialException("could not open port '/dev/ttyUSB0': FileNotFoundError(2, '系统找不到指定的路径。', None, 3)")}
2020-12-23 19:12:38,567 com_data.py[line:35] ERROR {'串口连接异常：': SerialException("could not open port '/dev/ttyUSB0': FileNotFoundError(2, '系统找不到指定的路径。', None, 3)")}
2020-12-23 19:47:53,516 com_data.py[line:35] ERROR {'串口连接异常：': SerialException("could not open port '/dev/ttyUSB0': FileNotFoundError(2, '系统找不到指定的路径。', None, 3)")}
2020-12-23 19:56:01,960 com_data.py[line:35] ERROR {'串口连接异常：': SerialException("could not open port '/dev/ttyUSB0': FileNotFoundError(2, '系统找不到指定的路径。', None, 3)")}
2020-12-23 19:56:52,282 com_data.py[line:35] ERROR {'串口连接异常：': SerialException("could not open port '/dev/ttyUSB0': FileNotFoundError(2, '系统找不到指定的路径。', None, 3)")}
2020-12-23 21:38:47,315 com_data.py[line:35] ERROR {'串口连接异常：': SerialException("could not open port '/dev/ttyUSB0': FileNotFoundError(2, '系统找不到指定的路径。', None, 3)")}
2020-12-23 21:48:04,851 com_data.py[line:35] ERROR {'串口连接异常：': SerialException("could not open port '/dev/ttyUSB0': FileNotFoundError(2, '系统找不到指定的路径。', None, 3)")}
2020-12-23 21:51:49,225 com_data.py[line:35] ERROR {'串口连接异常：': SerialException("could not open port '/dev/ttyUSB0': FileNotFoundError(2, '系统找不到指定的路径。', None, 3)")}
2020-12-23 21:53:09,210 com_data.py[line:35] ERROR {'串口连接异常：': SerialException("could not open port '/dev/ttyUSB0': FileNotFoundError(2, '系统找不到指定的路径。', None, 3)")}
2020-12-23 21:58:45,512 com_data.py[line:35] ERROR {'串口连接异常：': SerialException("could not open port '/dev/ttyUSB0': FileNotFoundError(2, '系统找不到指定的路径。', None, 3)")}
2020-12-23 21:59:55,779 com_data.py[line:35] ERROR {'串口连接异常：': SerialException("could not open port '/dev/ttyUSB0': FileNotFoundError(2, '系统找不到指定的路径。', None, 3)")}
2020-12-23 22:06:09,160 com_data.py[line:35] ERROR {'串口连接异常：': SerialException("could not open port '/dev/ttyUSB0': FileNotFoundError(2, '系统找不到指定的路径。', None, 3)")}
2020-12-23 22:08:14,832 com_data.py[line:35] ERROR {'串口连接异常：': SerialException("could not open port '/dev/ttyUSB0': FileNotFoundError(2, '系统找不到指定的路径。', None, 3)")}
2020-12-23 22:12:25,613 com_data.py[line:35] ERROR {'串口连接异常：': SerialException("could not open port '/dev/ttyUSB0': FileNotFoundError(2, '系统找不到指定的路径。', None, 3)")}
2020-12-23 22:26:16,816 com_data.py[line:35] ERROR {'串口连接异常：': SerialException("could not open port '/dev/ttyUSB0': FileNotFoundError(2, '系统找不到指定的路径。', None, 3)")}
